import {
  AddressEntity,
  ClientEntity,
  CompanyEntity,
  GroupEntity,
  GuaranteeEntity,
  LocalityEntity,
  MoralPersonEntity,
  PaymentOrderEntity,
  PhysicalPersonEntity,
  ProductEntity,
  ResetPasswordEntity,
  RevisionEntity,
  RevisionRequestEntity,
  UserEntity,
  VehicleEntity,
} from '@innovatech/api/domain';

export const ENTITIES = [
  AddressEntity,
  ClientEntity,
  CompanyEntity,
  GroupEntity,
  GuaranteeEntity,
  LocalityEntity,
  MoralPersonEntity,
  PaymentOrderEntity,
  PhysicalPersonEntity,
  ProductEntity,
  RevisionRequestEntity,
  ResetPasswordEntity,
  RevisionEntity,
  UserEntity,
  VehicleEntity,
];
