myapp-postgresql:
    image: postgres:9.6.2
    volumes:
        - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    environment:
        - POSTGRES_MULTIPLE_DATABASES=ivt,mrl,vma
