db:
  build: .
  ports:
    - "5432:5432"
  restart: always
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_MULTIPLE_DATABASES="innovatech","innovatech-test","music-revolution","music-revolution-test","valmira","valmira-test"
