import { IconDefinition } from '@ant-design/icons-angular';
import {
  ArrowLeftOutline,
  CheckCircleOutline,
  CloseCircleOutline,
  CloseOutline,
  DeleteOutline,
  DollarOutline,
  EditOutline,
  ExclamationCircleOutline,
  FacebookOutline,
  HomeOutline,
  InstagramOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  MinusOutline,
  MoreOutline,
  PlusCircleOutline,
  PlusOutline,
  PushpinOutline,
  SearchOutline,
  ShoppingOutline,
  WhatsAppOutline,
} from '@ant-design/icons-angular/icons';

export const icons: IconDefinition[] = [
  ArrowLeftOutline,
  CheckCircleOutline,
  CloseCircleOutline,
  CloseOutline,
  DeleteOutline,
  DollarOutline,
  EditOutline,
  ExclamationCircleOutline,
  FacebookOutline,
  HomeOutline,
  InstagramOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  MinusOutline,
  MoreOutline,
  PlusCircleOutline,
  PlusOutline,
  PushpinOutline,
  SearchOutline,
  ShoppingOutline,
  WhatsAppOutline,
];
