import {
  AdditionalOptionEntity,
  AddressEntity,
  CategoryEntity,
  CustomerEntity,
  OrderEntity,
  OrderProductAdditionalOptionEntity,
  OrderProductEntity,
  PriceOptionEntity,
  PriceOptionPhotoEntity,
  ProductComponentEntity,
  ProductEntity,
  ProductPhotoEntity,
  SocialEventEntity,
  SubcategoryEntity,
  UserEntity,
} from '@musicr/api/domain';

export const ENTITIES = [
  AdditionalOptionEntity,
  AddressEntity,
  CategoryEntity,
  CustomerEntity,
  OrderEntity,
  OrderProductAdditionalOptionEntity,
  OrderProductEntity,
  PriceOptionEntity,
  PriceOptionPhotoEntity,
  ProductComponentEntity,
  ProductEntity,
  ProductPhotoEntity,
  SocialEventEntity,
  SubcategoryEntity,
  UserEntity,
];
