import {
  AdditionalOptionEntity,
  AddressEntity,
  CategoryEntity,
  CustomerEntity,
  OrderEntity,
  OrderProductAdditionalOptionEntity,
  OrderProductEntity,
  PhotoEntity,
  PriceOptionEntity,
  ProductEntity,
  ResetPasswordEntity,
  SocialEventEntity,
  SubcategoryEntity,
  UserEntity,
} from '@musicr/api/domain';

export const ENTITIES = [
  AdditionalOptionEntity,
  AddressEntity,
  CategoryEntity,
  CustomerEntity,
  OrderEntity,
  OrderProductAdditionalOptionEntity,
  OrderProductEntity,
  PhotoEntity,
  PriceOptionEntity,
  ProductEntity,
  ResetPasswordEntity,
  SocialEventEntity,
  SubcategoryEntity,
  UserEntity,
];
