export const guaranteeExcelColumns: string[] = [
  'Folio',
  'Fecha de alta',
  'Fecha de actualización',
  'Estatus',
  'Compañía',
  'Fecha inicio',
  'Fecha fin',
  'Importe',
  'Fecha de factura',
  'Tipo de persona',
  'Nombre',
  'Apellido Paterno',
  'Apellido Materno',
  'Fecha de nacimiento',
  'Razón social',
  'Fecha de constitución',
  'Asesor',
  'RFC',
  'Teléfono',
  'Correo',
  'Código Postal',
  'País',
  'Estado',
  'Ciudad',
  'Colonia',
  'Calle',
  'Número Externo',
  'Número Interno',
  'Punto de Venta',
  'Producto',
  'Precio producto',
  'Marca',
  'Modelo',
  'Versión',
  'Año del vehículo',
  'HP',
  'VIN',
  'Nº de Motor',
  'Kilometraje inicial',
  'Fin garantía por kilometraje',
  'Creación orden de compra',
  'Actualización orden de compra',
  'Factura',
];
