import { IconDefinition } from '@ant-design/icons-angular';
import {
  BarcodeOutline,
  CarOutline,
  CheckCircleOutline,
  CloseCircleOutline,
  CloseOutline,
  ContainerOutline,
  DeleteOutline,
  DownOutline,
  EditOutline,
  ExclamationCircleOutline,
  ExportOutline,
  FallOutline,
  FileTextOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  MoreOutline,
  PieChartOutline,
  PlusCircleOutline,
  SearchOutline,
  SyncOutline,
  ToolOutline,
  UploadOutline,
  UsergroupAddOutline,
  UserOutline,
} from '@ant-design/icons-angular/icons';

export const icons: IconDefinition[] = [
  BarcodeOutline,
  CarOutline,
  CheckCircleOutline,
  CloseCircleOutline,
  CloseOutline,
  ContainerOutline,
  DeleteOutline,
  DownOutline,
  EditOutline,
  ExclamationCircleOutline,
  ExportOutline,
  FallOutline,
  FileTextOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  MoreOutline,
  PieChartOutline,
  PlusCircleOutline,
  SearchOutline,
  SyncOutline,
  ToolOutline,
  UploadOutline,
  UsergroupAddOutline,
  UserOutline,
];
