name: Music Revolution Staging API Deploy

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}
  HOST: ${{ secrets.MRL_STAGE_DB_HOST }}
  DB: ${{ secrets.MRL_STAGE_DB }}
  DB_USERNAME: ${{ secrets.MRL_STAGE_DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.MRL_STAGE_DB_PASSWORD }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: staging
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - uses: bahmutov/npm-install@v1

      - name: Run migrations
        run: npm run typeorm:musicr:run

      - name: Move Procfile
        run: mv ./apps/musicr/api/Procfile .

      - name: Build browser app
        run: export NODE_ENV=production && npx nx build musicr-store --prod

      - name: Build server app
        run: npx ng run musicr-store:server:production

      - name: Create zip file
        run: zip -r Archive.zip . -x .git/\* -x .cache/\* -x node_modules/\* -x .vscode/\*  -x .github/\* -x .tmp/\* -x apps/innovatech/\* -x apps/valmira/\* -x apps/pam-vic/\* -x apps/pam-vic-e2e/\* -x libs/innovatech/\* -x libs/valmira/\*

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID_EB }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_EB }}
          application_name: music-revolution
          environment_name: MRL-STAGE
          version_label: ${{ github.event.inputs.version }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: Archive.zip
          wait_for_environment_recovery: 120
