name: Staging Pull Request CI

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_BUCKET_NAME: arphase-photos-dev
  NODE_ENV: test
  IVT_DB: innovatech-test
  MRL_DB: music-revolution-test
  VMA_DB: valmira-test
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  SYNCHRONIZE: true
  JWT_SECRET: test
  JWT_EXPIRATION: 360000

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@v1

      - name: Setup Postgres container
        run: |
          docker-compose build
          docker-compose up -d

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install npm dependencies
        uses: bahmutov/npm-install@v1

      - name: Unit tests
        run: npx nx affected:test --base=remotes/origin/master --ci --runInBand
