name: Master Pull Request CI

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - uses: bahmutov/npm-install@v1

      - name: Run unit tests
        run: npx nx affected:test --base=remotes/origin/master --ci --runInBand
