# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Staging Pull Request CI

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

on:
  pull_request:
    branches:
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: git fetch --no-tags --prune --depth=5 origin staging

      - name: Install Dependencies
        run: npm ci

      - name: Run unit tests
        run: nx affected:test -- --base=origin/staging --ci --runInBand
