name: Staging Pull Request CI

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}
  NODE_ENV: test
  IVT_DB: ivt
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  SYNCHRONIZE: true
  JWT_SECRET: test
  JWT_EXPIRATION: 360000

on:
  pull_request:
    branches:
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@v1

      - name: Setup Postgres container
        run: |
          docker-compose build
          docker-compose up -d

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install npm dependencies
        uses: bahmutov/npm-install@v1

      - name: Innovatech DB seed
        run: npm run innovatech:seed

      - name: Unit tests
        run: npx nx affected:test --base=remotes/origin/staging --ci --runInBand
