name: Staging Pull Request CI

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}
  NODE_ENV: test
  IVT_DB: ivt
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  SYNCHRONIZE: true

on:
  pull_request:
    branches:
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:14.17.3

    services:
      postgres:
        image: postgres
        volumes:
          - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
        environment:
          - POSTGRES_MULTIPLE_DATABASES=ivt,mrl,vma
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: bahmutov/npm-install@v1

      - name: Run Innovatech DB seed
        run: npm run innovatech:seed

      - name: Run unit tests
        run: npx nx affected:test --base=remotes/origin/staging --ci --runInBand
